# Generated by Django 4.2.7 on 2023-11-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_alter_employees_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='EmployeeName',
            field=models.CharField(max_length=30),
        ),
    ]
