# Generated by Django 4.2.7 on 2023-11-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_employees_employeename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
