# Generated by Django 4.2.7 on 2023-11-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_alter_employees_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='DateOfJoining',
        ),
    ]
